### ISSUE TITLE
Automatic in-app remote notification popup

### ISSUE THREAD

**Issue by Montoya** [xu-li/cordova-plugin-parse#1]
Hi, just set up this plugin and it works great. The only concern I have is that when a notification arrives while the app is open, there is an automatic iOS popup. If I wanted to ingest the notification with my own callback and show my own custom popup, then I would have two popups! Is there a way to disable the built-in one?

**Comment by xu-li** [comment]
It may be possible. 

You may change the source code at [here](https://github.com/xu-li/cordova-plugin-parse/blob/master/src/ios/CDVParse.m#L63). So instead of requesting for badge, sound, and alert, you can only request for sound. (_WARNING: not tested._)

**Comment by Montoya** [comment]
I don't think that would achieve the desired result. I don't want to change the request on app startup, I like that. I want to change the behavior when a notification is received by the device. I'm fine with notifications behaving the way they do when the app is closed / in the background, my concern is how they behave when the app is in the foreground in iOS.

**Comment by xu-li** [comment]
Oh, I think the notification you see when your app is in foreground is created by parse.

Maybe you can check if your app is in foreground at [here](https://github.com/xu-li/cordova-plugin-parse/blob/master/src/ios/AppDelegate%2BCDVParse.m#L96).

So instead of `[PFPush handlePush:userInfo];`, use 

```
if (application.applicationState != UIApplicationStateActive ) {
    [PFPush handlePush:userInfo];
}
```

-Xu

**Comment by Montoya** [comment]
OK i think my original issue wasn't really an issue. The default behavior is nice when sending a default notification, and for notifications that I want to ingest / display differently, the trick is to use different JSON fields than the default and set up my callback function to use those fields. Closing this issue since it's not really an issue :)
